server:
  port: 10008
spring:
  application:
    name: PRODUCT-CLIENT
#    服务中心注册
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/
#      启用熔断
feign:
  hystrix:
    enabled: true